pipeline {
    agent any

    tools {
        gradle 'Gradle' // Configura Gradle en Jenkins (Manage Jenkins > Global Tool Configuration)
    }

    environment {
        SONARQUBE_ENV = 'sonarqube'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build and Test') {
            steps {
                sh './gradlew clean build'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv("${SONARQUBE_ENV}") {
                    sh './gradlew sonarqube -Dsonar.projectKey=sb-security-base'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t sb-security-base:latest .'
            }
        }
    }
}
