spring:
  datasource:
    url: jdbc:postgresql://dpg-d0lbtqnfte5s739c7q5g-a.oregon-postgres.render.com:5432/digitalbd
    username: digitaluser
    password: puwhx7IcmbFyotricRljNGtVp5BqqYzi
    driver-class-name: org.postgresql.Driver
  jpa:
    enabled: false
jwt:
  secret: Yz8nWpV2rQ5dBmX1sK9gLtA3vFzJeT7oN6uHbE4cXqMdRySaZwCoPlGtExHkUjNv
server:
  port: 8201